language: node_js
node_js:
 - "node"

 branches:
  only:
    - main
    - dev

cache: npm

script: 
  - yarn run test:unit
  - yarn run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GH_TOKEN
 local_dir: dist
 on:
   branch: main