language: node_js

node_js:
 - node

cache:
yarn: true
directories:
  - "node_modules"

branches:
only:
  - main

install:
  - yarn install

script:
  - yarn run test:unit
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: main