language: node_js
node_js:
 - "node"

cache: npm

script: 
  - yarn run test:unit
  - yarn run build


<<: &github_keyset
 github_token: $GH_TOKEN

<<: &deploy_setting
 skip_cleanup: true
 local_dir: dist

deploy:
 provider: pages
 <<: *github_keyset
 <<: *deploy_setting
 on:
   branch: main